-- Question 18: What is the total MRR generated by each plan?

SELECT plan_tier,
       SUM(mrr_amount) AS total_mrr
FROM subscriptions
GROUP BY plan_tier;

-- Question 19: What is the average MRR by plan?

SELECT plan_tier,
       AVG(mrr_amount) AS average_mrr
FROM subscriptions
GROUP BY plan_tier;

-- Question 20: How many customers belong to each country?

SELECT country,
       COUNT(*) AS customers
FROM accounts
GROUP BY country
ORDER BY customers DESC;

-- Question 21: How many customers belong to each industry?

SELECT industry,
       COUNT(*) AS customers
FROM accounts
GROUP BY industry
ORDER BY customers DESC;

-- Question 22: What is the average number of seats by plan?

SELECT plan_tier,
       AVG(seats) AS average_seats
FROM subscriptions
GROUP BY plan_tier;

-- Question 23: What is the average ARR by plan?

SELECT plan_tier,
       AVG(arr_amount) AS average_arr
FROM subscriptions
GROUP BY plan_tier;

-- Question 24: Which billing frequency is most common?

SELECT billing_frequency,
       COUNT(*) AS subscriptions
FROM subscriptions
GROUP BY billing_frequency;

-- Question 25: How many tickets exist for each priority level?

SELECT priority,
       COUNT(*) AS total_tickets
FROM support_tickets
GROUP BY priority
ORDER BY total_tickets DESC;