-- Question 30: Show customer names with their MRR.

SELECT
    a.account_name,
    s.mrr_amount
FROM accounts a
INNER JOIN subscriptions s
ON a.account_id = s.account_id;

-- Question 31: Show customer industry and plan.

SELECT
    a.account_name,
    a.industry,
    s.plan_tier
FROM accounts a
JOIN subscriptions s
ON a.account_id = s.account_id;

-- Question 32: Show customers and their support priorities.

SELECT
    a.account_name,
    t.priority
FROM accounts a
JOIN support_tickets t
ON a.account_id = t.account_id;

-- Question 33: Show churn reasons for customers.

SELECT
    a.account_name,
    c.reason_code
FROM accounts a
JOIN churn_events c
ON a.account_id = c.account_id;

-- Question 34: Find revenue generated by each industry.

SELECT
    a.industry,
    SUM(s.mrr_amount) AS total_revenue
FROM accounts a
JOIN subscriptions s
ON a.account_id = s.account_id
GROUP BY a.industry
ORDER BY total_revenue DESC;

-- Question 35: Find revenue generated by each country.

SELECT
    a.country,
    SUM(s.mrr_amount) AS total_revenue
FROM accounts a
JOIN subscriptions s
ON a.account_id = s.account_id
GROUP BY a.country
ORDER BY total_revenue DESC;

-- Question 36: Calculate average satisfaction by industry.

SELECT
    a.industry,
    AVG(t.satisfaction_score) AS avg_satisfaction
FROM accounts a
JOIN support_tickets t
ON a.account_id = t.account_id
WHERE satisfaction_score > 0
GROUP BY a.industry;

-- Question 37: Count support tickets by country.

SELECT
    a.country,
    COUNT(t.ticket_id) AS total_tickets
FROM accounts a
JOIN support_tickets t
ON a.account_id = t.account_id
GROUP BY a.country
ORDER BY total_tickets DESC;

-- Question 38: Find churn count by industry.

SELECT
    a.industry,
    COUNT(c.churn_event_id) AS churn_count
FROM accounts a
JOIN churn_events c
ON a.account_id = c.account_id
GROUP BY a.industry
ORDER BY churn_count DESC;

-- Question 39: Show customers that have never churned.

SELECT
    a.account_name,
    c.churn_event_id
FROM accounts a
LEFT JOIN churn_events c
ON a.account_id = c.account_id
WHERE c.churn_event_id IS NULL;

-- Question 40: Which churn reasons are associated with support priorities?

SELECT
    t.priority,
    c.reason_code,
    COUNT(*) AS total_cases

FROM support_tickets t

JOIN churn_events c
ON t.account_id = c.account_id

GROUP BY
    t.priority,
    c.reason_code

ORDER BY total_cases DESC;
 